steps:
  - label: ":hammer: Install"
    command: "npm install"
    key: install

  - label: ":test_tube: Build $$Server"
    command: "npm run build $$Server"
    env:
      SERVER: 'test'
    key: build
    depends_on: install
