steps:
  - label: ":hammer: Install"
    command: "npm install"
    key: install

  - block: 'Are we ready'
    
  - label: 'echo'
    command: "echo 'Hello'"
  - label: ":test_tube: Build ${SERVER}"
    command: "npm run build $$SERVER"
    env:
      SERVER: 'test'
    key: build
    depends_on: install
