steps:
  - label: ":hammer: Install"
    command: "npm install"
    key: install

  - block: "Release"
    prompt: "Fill out the details for release"
    fields:
      - text: "Release Name"
        key: "release-name"

    
  - label: 'echo'
    command: "echo 'Hello'"
