steps:
  - label: ":hammer: Install"
    command: "npm install"
    key: install

  - block: "Release"
    prompt: "Fill out the details for release"
    fields:
      - text: "Release Name"
        key: "release-name"

    
  - label: 'echo'
    command: "echo 'Hello'"
  - label: ":test_tube: Build ${SERVER}"
    command: "npm run build $$SERVER"
    env:
      SERVER: 'test'
    key: build
    depends_on: install
